;; Object exception_test/
;; SEMANTICDB Tags save file
(semanticdb-project-database-file "exception_test/"
  :tables
  (list
    (semanticdb-table "main.py"
      :major-mode 'python-mode
      :tags 
        '( ("myexceptions" include nil nil [1 26])
            ("base" include nil nil [67 92]))          
      :file "main.py"
      :pointmax 234
      :fsize 245
      :lastmodtime '(22017 14276 0 0)
      :unmatched-syntax '((INDENT_BLOCK 191 . 234) (COLON 189 . 190) (AS 185 . 187) (EXCEPT 168 . 174) (INDENT_BLOCK 143 . 168) (COLON 141 . 142) (TRY 94 . 97) (AS 137 . 139) (INDENT_BLOCK 188 . 231) (COLON 186 . 187) (AS 182 . 184) (EXCEPT 165 . 171) (INDENT_BLOCK 140 . 165) (COLON 138 . 139) (TRY 94 . 97) (AS 134 . 136) (INDENT_BLOCK 191 . 234) (COLON 189 . 190) (AS 185 . 187) (EXCEPT 168 . 174) (INDENT_BLOCK 143 . 168) (COLON 141 . 142) (TRY 94 . 97) (AS 137 . 139) (INDENT_BLOCK 191 . 234) (COLON 189 . 190) (AS 185 . 187) (EXCEPT 168 . 174) (INDENT_BLOCK 143 . 168) (COLON 141 . 142) (TRY 94 . 97) (AS 137 . 139)))
    (semanticdb-table "myexceptions.py"
      :major-mode 'python-mode
      :tags 
        '( ("TheException" type
               (:superclasses ("Exception")
                :members 
                  ( ("pass" code nil (reparse-symbol indented_block_body) [36 40]))                  
                :type "class")
                nil [1 41]))          
      :file "myexceptions.py"
      :pointmax 41
      :fsize 42
      :lastmodtime '(22017 9179 0 0)
      :unmatched-syntax nil)
    (semanticdb-table "base.py"
      :major-mode 'python-mode
      :tags 
        '( ("myexceptions" include nil nil [43 68])
            ("function" function nil nil [109 185]))          
      :file "base.py"
      :pointmax 185
      :fsize 191
      :lastmodtime '(22017 14287 0 0)
      :unmatched-syntax nil))
  :file "!drive_c!Users!sebastian.haas!workspace!rnd!exception_test!semantic.cache"
  :semantic-tag-version "2.0"
  :semanticdb-version "2.2")
